services:
  - type: web
    name: nba-prop-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ODDS_API_KEY
        value: a03349ac7178eb60a825d19bd27014ce
